name: PingPlayer
api: 4.0.0
main: Ping\Main
author: AxelFeL
version: 1

commands:
  ping:
    description: Find Out Your Ping
    permission: ping.cmd

permissions:
  ping.cmd:
    description: Ping Command Permission
    default: true
